docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - "Code Generation": 
        - Intro: generator/intro.md
        - Examples: generator/examples.md
        - Reference: generator/reference.md
    - Migration: migration.md
site_name: laminas-code
site_description: 'laminas-code: Tools for reflecting, scanning, and generating PHP code'
repo_url: 'https://github.com/laminas/laminas-code'
